<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/04/13 01:04:43

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=hockey',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
